#!/bin/bash

OAI_BUILD_DIR="ext/openair/cmake_targets/ran_build/build"

for lib in ${OAI_BUILD_DIR}/*.a; do
    if nm $lib | grep -q $1; then
        echo "FOUND in $lib"
    fi
done

for lib in ${OAI_BUILD_DIR}/lib*.so*; do
    if nm -D $lib | grep -q $1; then
        echo "FOUND in $lib"
    fi
done