server:
  persistentVolume:
    enabled: false

extraScrapeConfigs: |-
  - job_name: 'kepler'
    scrape_interval: 5s
    scrape_timeout: 2s
    static_configs:
      # Kepler v0.11.3 default listen address is :28282 (from ConfigMap web.listenAddresses)
      - targets: ['kepler.kepler:28282']

alertmanager:
  enabled: false
prometheus-pushgateway:
  enabled: false
prometheus-node-exporter:
  enabled: false
kubeStateMetrics:
  enabled: false
